#!/usr/bin/env bash
# Build memory/index.md from journal front matter: recipe id -> entries.
# Deterministic, no model, no network. See docs/memory.md.
set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"
journal="$root/memory/journal"
index="$root/.rampa/index.md"

mkdir -p "$root/.rampa"
[ -d "$journal" ] || { echo "No journal yet at memory/journal/ — nothing to index."; exit 0; }

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

# One "recipe<TAB>entry (scope, status)" line per (entry, recipe) pair.
for f in "$journal"/*.md; do
    [ -e "$f" ] || continue
    rel="journal/$(basename "$f")"
    fm=$(awk 'NR==1 && /^---$/{f=1;next} f && /^---$/{exit} f' "$f")
    recipes=$(printf '%s\n' "$fm" | sed -n 's/^recipes:[[:space:]]*\[\(.*\)\]$/\1/p' | tr -d ' ' | tr ',' '\n')
    scope=$(printf '%s\n' "$fm" | sed -n 's/^scope:[[:space:]]*//p')
    status=$(printf '%s\n' "$fm" | sed -n 's/^status:[[:space:]]*//p')
    [ -z "$recipes" ] && recipes="(unattributed)"
    while IFS= read -r r; do
        [ -z "$r" ] && continue
        printf '%s\t%s (%s, %s)\n' "$r" "$rel" "${scope:-?}" "${status:-?}" >> "$tmp"
    done <<< "$recipes"
done

{
    echo "<!-- generated by scripts/memory-index.sh — do not edit -->"
    echo
    if [ ! -s "$tmp" ]; then
        echo "_No journal entries yet._"
    else
        current=""
        while IFS=$'\t' read -r recipe entry; do
            if [ "$recipe" != "$current" ]; then
                [ -n "$current" ] && echo
                echo "## $recipe"
                current="$recipe"
            fi
            echo "- $entry"
        done < <(sort "$tmp")
    fi
} > "$index"

echo "✓ $index"
