import type { Vault } from '../vault/io.js';
import { VAULT } from '../vault/paths.js';
import { parseFrontMatter } from '../vault/parse.js';
import { journalEntrySchema, validateWithRepair, type JournalEntry } from '../vault/schema.js';

/**
 * Memory: three scopes, and the teacher routes every item (Principle VIII).
 *
 * Only she knows whether "don't split this" means not for this child, not in
 * this school, or never. Guessing wrong in the third direction sends
 * learner-specific information into shared material, which is a privacy
 * incident rather than a quality problem — so nothing here infers a scope.
 */
export type Scope = 'learner' | 'practice' | 'corpus';

export interface JournalDoc extends JournalEntry { path: string; body: string; }

export async function loadJournal(vault: Vault): Promise<JournalDoc[]> {
  const files = await vault.list(VAULT.journal);
  const out: JournalDoc[] = [];
  for (const f of files) {
    if (!f.endsWith('.md')) continue;
    const path = `${VAULT.journal}/${f}`;
    const raw = await vault.readRaw(path);
    if (raw === null) continue;
    const { data, body } = parseFrontMatter(raw, path);
    const { value } = validateWithRepair(journalEntrySchema, data, path);
    if (!value.date) continue;
    out.push({ ...value, path, body });
  }
  return out;
}

/** recipe id → entries. Derived, never hand-edited. Deterministic: no model. */
export function buildIndex(entries: JournalDoc[]): string {
  const byRecipe = new Map<string, JournalDoc[]>();
  for (const e of entries) {
    for (const r of e.recipes.length ? e.recipes : ['(sin receta)']) {
      (byRecipe.get(r) ?? byRecipe.set(r, []).get(r)!).push(e);
    }
  }
  const lines = ['<!-- generated by Rampa — do not edit -->', ''];
  if (byRecipe.size === 0) { lines.push('_Todavía no hay entradas en el diario._'); return lines.join('\n') + '\n'; }
  for (const recipe of [...byRecipe.keys()].sort()) {
    lines.push(`## ${recipe}`);
    for (const e of byRecipe.get(recipe)!.sort((a, b) => a.path.localeCompare(b.path))) {
      lines.push(`- ${e.path.replace(VAULT.memory + '/', '')} (${e.scope}, ${e.status})`);
    }
    lines.push('');
  }
  return lines.join('\n');
}

export async function writeIndex(vault: Vault, entries: JournalDoc[]): Promise<void> {
  await vault.writeRaw(VAULT.index, buildIndex(entries));
}

/**
 * What a run loads. The journal is never read wholesale (003 FR-207): only
 * entries for the recipes actually selected reach the model, so memory load
 * does not grow with journal size.
 */
export interface LoadedMemory { house: string; journal: JournalDoc[]; }

export async function loadForRun(vault: Vault, selectedRecipeIds: readonly string[]): Promise<LoadedMemory> {
  const house = (await vault.readRaw(VAULT.house)) ?? '';
  const all = await loadJournal(vault);
  const wanted = new Set(selectedRecipeIds);
  return {
    house,
    journal: all.filter((e) => e.status !== 'archived' && e.recipes.some((r) => wanted.has(r))),
  };
}

/** House style is a style guide, not a log. Past this it has become one. */
export const HOUSE_STYLE_LIMIT_CHARS = 6000;
export const houseStyleOverflowing = (house: string): boolean => house.length > HOUSE_STYLE_LIMIT_CHARS;
