import { describe, it, expect, vi } from 'vitest';
import { mkdtemp, rm, readdir, readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, dirname } from 'node:path';
import { Vault, parseSelection, activationOf, SELECTION_PATH } from '@rampa/core';

/**
 * Two boundaries mocked, and only the boundaries.
 *
 * `electron` because `ipc/wrap.js` reaches for `ipcMain` at import time, and this suite
 * runs with no Electron at all — the same reason `test:isolation` exists.
 *
 * `bundle.js` because `corpusRoot()` resolves to `app/corpus/`, which is **generated**
 * by `bundle-corpus.mjs` and is not regenerated by `npm run test:all`. A test reading it
 * would pass or fail on whether somebody had run `npm run dev` recently. So the reader
 * is replaced with one that reads `instructions/normative/` — the actual source of
 * truth — which makes this test read the real shipped corpus rather than a copy of it.
 */
vi.mock('electron', () => ({ ipcMain: { handle: () => {} }, app: {}, dialog: {}, shell: {} }));
vi.mock('../src/corpus/bundle.js', () => ({
  readBundledDir: async (...segments: string[]) => {
    const dir = join(repoRoot, ...segments);
    const names = await readdir(dir).catch(() => [] as string[]);
    return Promise.all(names.filter((n) => n.endsWith('.md')).map(async (n) => ({
      path: join(dir, n), raw: await readFile(join(dir, n), 'utf8'),
    })));
  },
}));

const repoRoot = join(dirname(new URL(import.meta.url).pathname), '..', '..', '..', '..');

const { availableCorpora, normativeFor, readSelection, writeSelection, sha256 } =
  await import('../src/corpus/normative.js');

/**
 * Where a corpus comes from, and which one is in force (029 T008, FR-2701/2706/2711).
 *
 * Origin is **derived** here and stored nowhere. An `origin:` field in the file would be
 * a stored copy of what the filesystem already says — the two-copies defect — and it
 * would start lying the moment somebody copied a file. The one thing that is stored is
 * the activation hash, and it earns its place: without it, «modificado por ti» would
 * need a second copy of her file to diff against, or would be undetectable.
 */
const scratch = () => mkdtemp(join(tmpdir(), 'rampa-normative-'));

const corpusFile = (id: string, label: string) =>
  `---\nid: ${id}\nlabel: ${label}\nregister: Su plataforma\n---\n\n# ${label}\n\nSu texto.\n`;

describe('what she can pick from', () => {
  it('the bundled corpora are there with no vault at all', async () => {
    /*
     * A teacher who has not chosen a folder yet still gets a truthful answer: the
     * shipped corpora exist and the resolved normativa is generic. That is why the
     * loader takes `Vault | null` rather than catching `currentVault`'s throw to arrive
     * at the same place.
     */
    const available = await availableCorpora(null);
    expect(available.map((a) => a.corpus.id)).toContain('es-an');
    expect(available.every((a) => a.origin === 'bundled')).toBe(true);
  });

  it('and the README is not one of them', async () => {
    // It is documentation for whoever writes the Galician one, not a territory.
    const available = await availableCorpora(null);
    expect(available.some((a) => a.corpus.label.includes('Normativa'))).toBe(false);
  });

  it('her own files come through as «subido»', async () => {
    const dir = await scratch();
    const vault = new Vault(dir);
    await vault.writeRaw('normative/madrid.md', corpusFile('es-md', 'Madrid'));

    const mine = (await availableCorpora(vault)).find((a) => a.corpus.id === 'es-md');
    expect(mine?.origin).toBe('subido');
    await rm(dir, { recursive: true, force: true });
  });

  it('a vault file claiming a shipped id does not become the corpus in force', async () => {
    /*
     * The whole point of listing bundled first. A downloaded «es-an.md» that replaced
     * the shipped one would draft documents under a territory's name with somebody
     * else's content, and the provenance line would say «Andalucía, incluido con Rampa».
     */
    const dir = await scratch();
    const vault = new Vault(dir);
    await vault.writeRaw('normative/no-andalucia.md', corpusFile('es-an', 'No es Andalucía'));

    const found = (await availableCorpora(vault)).filter((a) => a.corpus.id === 'es-an');
    expect(found).toHaveLength(1);
    expect(found[0]!.corpus.label).toBe('Andalucía');
    expect(found[0]!.origin).toBe('bundled');
    await rm(dir, { recursive: true, force: true });
  });

  it('selection.md is in that directory and is not offered as a corpus', async () => {
    const dir = await scratch();
    const vault = new Vault(dir);
    await writeSelection(vault, { selected: 'es-an', activations: [], body: '' });
    const available = await availableCorpora(vault);
    expect(available.map((a) => a.corpus.id)).toEqual(['es-an']);
    await rm(dir, { recursive: true, force: true });
  });

  it('and it stays excluded BY NAME, not by happening to lack an id', async () => {
    /*
     * The first version of this passed for the wrong reason: `selection.md` has no
     * `id`, so the parser dropped it anyway and deleting the exclusion changed nothing.
     * Mutation found that.
     *
     * The exclusion has to be by name, because `selection.md` is **Rampa's own
     * bookkeeping**, not her content — the same confusion that made `031` treat
     * `ir.md` as a learner code. A selection file that grew an `id:` field one day
     * would otherwise appear in her picker as a normativa she could select, activate
     * and draft documents under.
     */
    const dir = await scratch();
    const vault = new Vault(dir);
    await vault.writeRaw(SELECTION_PATH,
      '---\nselected: es-an\nid: selection\nlabel: No soy una normativa\n---\n\n');
    const available = await availableCorpora(vault);
    expect(available.map((a) => a.corpus.id)).not.toContain('selection');
    await rm(dir, { recursive: true, force: true });
  });
});

describe('«modificado por ti», derived from the activation hash', () => {
  it('an activated file that has not changed is still «subido»', async () => {
    const dir = await scratch();
    const vault = new Vault(dir);
    const raw = corpusFile('es-md', 'Madrid');
    await vault.writeRaw('normative/madrid.md', raw);
    await writeSelection(vault, {
      selected: 'es-md', body: '',
      activations: [{
        corpus: 'es-md', on: '2026-09-10', contentSha256: sha256(raw),
        findings: 0, overridden: false,
      }],
    });

    const found = (await availableCorpora(vault)).find((a) => a.corpus.id === 'es-md');
    expect(found?.origin).toBe('subido');
    await rm(dir, { recursive: true, force: true });
  });

  it('and one edited since says so, which is visibility and not punishment', async () => {
    const dir = await scratch();
    const vault = new Vault(dir);
    await vault.writeRaw('normative/madrid.md', corpusFile('es-md', 'Madrid'));
    await writeSelection(vault, {
      selected: 'es-md', body: '',
      activations: [{
        corpus: 'es-md', on: '2026-09-10', contentSha256: sha256('lo que activó'),
        findings: 0, overridden: false,
      }],
    });

    const found = (await availableCorpora(vault)).find((a) => a.corpus.id === 'es-md');
    expect(found?.origin).toBe('modificado');
    // And the sentence in the document says it.
    const resolved = await normativeFor(vault);
    expect(resolved.provenanceLine).toContain('modificado después');
    await rm(dir, { recursive: true, force: true });
  });

  it('a file she dropped in by hand, never activated, is «subido» and not «modificado»', async () => {
    /*
     * Dropping a Markdown file into her own vault is a legitimate thing to do. Calling
     * it «modificado» would be reporting an edit she never made — and the guarantee the
     * import flow adds is the **scan**, not the existence of a hash.
     */
    const dir = await scratch();
    const vault = new Vault(dir);
    await vault.writeRaw('normative/galicia.md', corpusFile('es-ga', 'Galicia'));
    const found = (await availableCorpora(vault)).find((a) => a.corpus.id === 'es-ga');
    expect(found?.origin).toBe('subido');
    await rm(dir, { recursive: true, force: true });
  });
});

describe('the selection file', () => {
  it('round-trips, and keeps her own notes in the body', async () => {
    const dir = await scratch();
    const vault = new Vault(dir);
    await writeSelection(vault, {
      selected: 'es-an', body: 'Lo cambié en septiembre porque me mudé de centro.',
      activations: [{
        corpus: 'es-an', on: '2026-09-10', contentSha256: 'abc',
        findings: 2, overridden: true,
      }],
    });

    const back = await readSelection(vault);
    expect(back.selected).toBe('es-an');
    expect(back.body).toContain('me mudé de centro');
    expect(activationOf(back, 'es-an')?.findings).toBe(2);
    await rm(dir, { recursive: true, force: true });
  });

  it('no file at all is generic, without a notice, because nothing went missing', async () => {
    const dir = await scratch();
    const vault = new Vault(dir);
    const resolved = await normativeFor(vault);
    expect(resolved.of).toBe('generic');
    expect(resolved.of === 'generic' && resolved.because).toBe('nothing-selected');
    expect(resolved.provenanceLine).not.toContain('Ojo');
    await rm(dir, { recursive: true, force: true });
  });

  it('a selected corpus that is gone gives generic WITH the notice', async () => {
    const dir = await scratch();
    const vault = new Vault(dir);
    await writeSelection(vault, { selected: 'es-ga', activations: [], body: '' });
    const resolved = await normativeFor(vault);
    expect(resolved.of === 'generic' && resolved.because).toBe('selected-missing');
    expect(resolved.provenanceLine).toContain('es-ga');
    await rm(dir, { recursive: true, force: true });
  });

  it('an activation with findings and no recorded override is read as not activated', async () => {
    /*
     * Refuse-don't-repair. Either the override was lost or something wrote the entry
     * while skipping the decision; treating it as activated would put a scanned-and-
     * flagged policy file into force on the strength of a malformed line.
     */
    const parsed = parseSelection(
      '---\nselected: x\nactivations:\n  - corpus: x\n    on: "2026-09-10"\n'
      + '    content_sha256: abc\n    findings: 3\n---\n\n', SELECTION_PATH);
    expect(parsed.activations).toEqual([]);
    expect(activationOf(parsed, 'x')).toBeUndefined();
  });

  it('and the same entry with the override recorded is an activation', async () => {
    const parsed = parseSelection(
      '---\nselected: x\nactivations:\n  - corpus: x\n    on: "2026-09-10"\n'
      + '    content_sha256: abc\n    findings: 3\n    overridden: true\n---\n\n', SELECTION_PATH);
    expect(activationOf(parsed, 'x')?.overridden).toBe(true);
  });

  it('the newest activation for a corpus is the one in force', async () => {
    // Re-activating after an edit is the ordinary way a corpus changes.
    const parsed = parseSelection(
      '---\nactivations:\n  - corpus: x\n    on: "2026-01-01"\n    content_sha256: viejo\n'
      + '  - corpus: x\n    on: "2026-09-10"\n    content_sha256: nuevo\n---\n\n', SELECTION_PATH);
    expect(activationOf(parsed, 'x')?.contentSha256).toBe('nuevo');
  });
});

describe('the learner override, through the loader', () => {
  it('`none` on the profile forces generic even with a corpus selected', async () => {
    const dir = await scratch();
    const vault = new Vault(dir);
    await writeSelection(vault, { selected: 'es-an', activations: [], body: '' });

    expect((await normativeFor(vault)).of).toBe('corpus');
    const forced = await normativeFor(vault, 'none');
    expect(forced.of).toBe('generic');
    expect(forced.of === 'generic' && forced.because).toBe('learner-override');
    await rm(dir, { recursive: true, force: true });
  });
});
