import { describe, it, expect, vi } from 'vitest';
import { readFileSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { checkForUpdate } from '@rampa/providers';

/**
 * The machinery exists and the application still works with no network (034 T001,
 * FR-3202, SC-3202).
 *
 * ## Why this is written first, and why it is the invariant rather than a feature test
 *
 * Because the failure is silent in both directions. A check that fires without her
 * consent produces no symptom she can see; a check that fails and surfaces an error
 * produces one that looks like the application being broken. Neither is caught by
 * testing that the check works.
 *
 * A teacher in a school with no outbound HTTP — which is most of them at 9am — must
 * notice nothing at all.
 */
const repoRoot = join(dirname(new URL(import.meta.url).pathname), '..', '..', '..', '..');

vi.mock('electron', () => ({ ipcMain: { handle: () => {} }, app: {}, dialog: {}, shell: {} }));
/*
 * The corpus reader, pointed at `instructions/` — `app/corpus/` is generated by
 * `bundle-corpus.mjs`, which `npm run test:all` does not run, so reading it would pass
 * or fail on when somebody last ran `npm run dev`.
 */
vi.mock('../src/corpus/bundle.js', async (original) => ({
  ...(await original<Record<string, unknown>>()),
  readBundledFile: async (...segments: string[]) =>
    readFileSync(join(repoRoot, ...segments), 'utf8'),
}));

describe('with no network at all', () => {
  it('a check is silence: an answer she can read, never an error', async () => {
    /*
     * `checkForUpdate` never throws — a failed check is a sentence. And the sentence is
     * about *her* situation («ahora no») rather than about a status code, because the
     * person reading it is a teacher and «HTTP 503» is not information she can act on.
     */
    const said = await checkForUpdate('0.4.0', {
      api: 'https://127.0.0.1:1/nada', timeoutMs: 50,
    });
    expect(said.problem).toBe('offline');
    expect(said.newer).toBe(false);
    expect(said.current).toBe('0.4.0');
    // And it still hands her the page, so «no he podido mirar» is not a dead end.
    expect(said.page).toContain('github.com');
  });

  it('and it is one call that returns, not a hang', async () => {
    // Bounded time per request. A check that hangs is a launch that hangs, once the
    // consent toggle exists.
    const started = Date.now();
    await checkForUpdate('0.4.0', { api: 'https://127.0.0.1:1/nada', timeoutMs: 50 });
    expect(Date.now() - started).toBeLessThan(4000);
  });
});

describe('nothing reaches the network unless it is asked to', () => {
  it('everything that can reach the network is enumerated, with a reason each', () => {
    /*
     * Asserted as **structure** rather than by counting requests, and as a **list**
     * rather than as «zero»: `023` gave the shell a legitimate fetcher, so «only
     * providers reaches out» stopped being true and the honest guard is the one that
     * names who does.
     *
     * `packages/core` is the one that must stay at zero — `npm run test:isolation`
     * already enforces it, and this restates it from the update side because that is
     * where the next `fetch` would be tempting.
     */
    const walk = (dir: string): string[] => {
      const out: string[] = [];
      for (const e of readdirSync(dir, { withFileTypes: true })) {
        const p = join(dir, e.name);
        if (e.isDirectory()) out.push(...walk(p));
        else if (/\.tsx?$/.test(p) && !/\.test\.tsx?$/.test(p)) out.push(p);
      }
      return out;
    };
    const reachers = (dir: string) => walk(dir)
      .filter((f) => {
        const code = readFileSync(f, 'utf8')
          .replace(/\/\*[\s\S]*?\*\//g, '').replace(/^[ \t]*\/\/.*$/gm, '');
        return /\bfetch\s*\(|new XMLHttpRequest|from 'node:https?'/.test(code);
      })
      .map((f) => f.replace(`${repoRoot}/`, ''))
      .sort();

    // Principle II, from the update side: the deterministic core reaches nothing.
    expect(reachers(join(repoRoot, 'app', 'packages', 'core', 'src'))).toEqual([]);

    expect([
      ...reachers(join(repoRoot, 'app', 'packages', 'shell', 'src')),
      ...reachers(join(repoRoot, 'app', 'ui', 'src')),
    ]).toEqual([
      // `023`'s pictogram download: her explicit act, behind the licence gate, in the
      // main process — and the gate mints the transport so a second caller cannot
      // bypass it.
      'app/packages/shell/src/pictograms/download.ts',
      /*
       * And the renderer's side of it, which reaches nothing itself: `ui/src/data/`
       * only ever calls `window.rampa`. It is in this list because the word appears —
       * which is the cost of a grep, and cheaper than a filter somebody edits.
       */
      'app/ui/src/data/pictograms.ts',
    ]);
  });

  it('and the destinations are declared in the corpus, not hardcoded in the reachers', async () => {
    /*
     * FR-3204, and it is the disclosure and the permission being **one list**. Two lists
     * do not fail by the code reaching somewhere undeclared; they fail by a third
     * destination being added and the screen still saying two.
     */
    const { updateDestinations } = await import('../src/corpus/destinations.js');
    const declared = await updateDestinations();
    expect(declared.length).toBeGreaterThan(2);
    for (const d of declared) {
      expect(d.url.startsWith('https://'), d.id).toBe(true);
      // Every one says when it happens and what it sends, because that is what she is
      // being told, not just where it goes.
      expect(d.when, d.id).not.toBe('');
      expect(d.sends, d.id).not.toBe('');
    }
    expect(declared.map((d) => d.host)).toContain('api.github.com');
  });

  it('and nothing in the update surface holds a reference to a learner', () => {
    /*
     * The other half of «offline is safe»: what would be *sent* if a request happened.
     * The update path has no vault, no learner code and no profile in it — a check
     * carries the request and nothing else, and that is enforced by the update files
     * having nothing else to carry.
     */
    const files = [
      join(repoRoot, 'app', 'packages', 'providers', 'src', 'releases.ts'),
      join(repoRoot, 'app', 'packages', 'shell', 'src', 'corpus', 'destinations.ts'),
      join(repoRoot, 'app', 'packages', 'core', 'src', 'corpus-update', 'manifest.ts'),
    ];
    for (const f of files) {
      const code = readFileSync(f, 'utf8')
        .replace(/\/\*[\s\S]*?\*\//g, '').replace(/^[ \t]*\/\/.*$/gm, '');
      for (const word of ['learnerCode', 'currentVault', 'loadLearner', 'profile.']) {
        expect(code, `${f} · ${word}`).not.toContain(word);
      }
    }
  });
});
