import { describe, it, expect, vi } from 'vitest';
import { readFileSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { mkdtemp, writeFile, rm, readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { checkForUpdate } from '@rampa/providers';

/**
 * The machinery exists and the application still works with no network (034 T001,
 * FR-3202, SC-3202).
 *
 * ## Why this is written first, and why it is the invariant rather than a feature test
 *
 * Because the failure is silent in both directions. A check that fires without her
 * consent produces no symptom she can see; a check that fails and surfaces an error
 * produces one that looks like the application being broken. Neither is caught by
 * testing that the check works.
 *
 * A teacher in a school with no outbound HTTP — which is most of them at 9am — must
 * notice nothing at all.
 */
const repoRoot = join(dirname(new URL(import.meta.url).pathname), '..', '..', '..', '..');

vi.mock('electron', () => ({ ipcMain: { handle: () => {} }, app: {}, dialog: {}, shell: {} }));
/*
 * The corpus reader, pointed at `instructions/` — `app/corpus/` is generated by
 * `bundle-corpus.mjs`, which `npm run test:all` does not run, so reading it would pass
 * or fail on when somebody last ran `npm run dev`.
 */
vi.mock('../src/corpus/bundle.js', async (original) => ({
  ...(await original<Record<string, unknown>>()),
  readBundledFile: async (...segments: string[]) =>
    readFileSync(join(repoRoot, ...segments), 'utf8'),
}));

describe('with no network at all', () => {
  it('a check is silence: an answer she can read, never an error', async () => {
    /*
     * `checkForUpdate` never throws — a failed check is a sentence. And the sentence is
     * about *her* situation («ahora no») rather than about a status code, because the
     * person reading it is a teacher and «HTTP 503» is not information she can act on.
     */
    const said = await checkForUpdate('0.4.0', {
      api: 'https://127.0.0.1:1/nada', timeoutMs: 50,
    });
    expect(said.problem).toBe('offline');
    expect(said.newer).toBe(false);
    expect(said.current).toBe('0.4.0');
    // And it still hands her the page, so «no he podido mirar» is not a dead end.
    expect(said.page).toContain('github.com');
  });

  it('and it is one call that returns, not a hang', async () => {
    // Bounded time per request. A check that hangs is a launch that hangs, once the
    // consent toggle exists.
    const started = Date.now();
    await checkForUpdate('0.4.0', { api: 'https://127.0.0.1:1/nada', timeoutMs: 50 });
    expect(Date.now() - started).toBeLessThan(4000);
  });
});

describe('nothing reaches the network unless it is asked to', () => {
  it('everything that can reach the network is enumerated, with a reason each', () => {
    /*
     * Asserted as **structure** rather than by counting requests, and as a **list**
     * rather than as «zero»: `023` gave the shell a legitimate fetcher, so «only
     * providers reaches out» stopped being true and the honest guard is the one that
     * names who does.
     *
     * `packages/core` is the one that must stay at zero — `npm run test:isolation`
     * already enforces it, and this restates it from the update side because that is
     * where the next `fetch` would be tempting.
     */
    const walk = (dir: string): string[] => {
      const out: string[] = [];
      for (const e of readdirSync(dir, { withFileTypes: true })) {
        const p = join(dir, e.name);
        if (e.isDirectory()) out.push(...walk(p));
        else if (/\.tsx?$/.test(p) && !/\.test\.tsx?$/.test(p)) out.push(p);
      }
      return out;
    };
    const reachers = (dir: string) => walk(dir)
      .filter((f) => {
        const code = readFileSync(f, 'utf8')
          .replace(/\/\*[\s\S]*?\*\//g, '').replace(/^[ \t]*\/\/.*$/gm, '');
        return /\bfetch\s*\(|new XMLHttpRequest|from 'node:https?'/.test(code);
      })
      .map((f) => f.replace(`${repoRoot}/`, ''))
      .sort();

    // Principle II, from the update side: the deterministic core reaches nothing.
    expect(reachers(join(repoRoot, 'app', 'packages', 'core', 'src'))).toEqual([]);

    expect([
      ...reachers(join(repoRoot, 'app', 'packages', 'shell', 'src')),
      ...reachers(join(repoRoot, 'app', 'ui', 'src')),
    ]).toEqual([
      // `023`'s pictogram download: her explicit act, behind the licence gate, in the
      // main process — and the gate mints the transport so a second caller cannot
      // bypass it.
      'app/packages/shell/src/pictograms/download.ts',
      /*
       * And the renderer's side of it, which reaches nothing itself: `ui/src/data/`
       * only ever calls `window.rampa`. It is in this list because the word appears —
       * which is the cost of a grep, and cheaper than a filter somebody edits.
       */
      'app/ui/src/data/pictograms.ts',
    ]);
  });

  it('and the destinations are declared in the corpus, not hardcoded in the reachers', async () => {
    /*
     * FR-3204, and it is the disclosure and the permission being **one list**. Two lists
     * do not fail by the code reaching somewhere undeclared; they fail by a third
     * destination being added and the screen still saying two.
     */
    const { updateDestinations } = await import('../src/corpus/destinations.js');
    const declared = await updateDestinations();
    expect(declared.length).toBeGreaterThan(2);
    for (const d of declared) {
      expect(d.url.startsWith('https://'), d.id).toBe(true);
      // Every one says when it happens and what it sends, because that is what she is
      // being told, not just where it goes.
      expect(d.when, d.id).not.toBe('');
      expect(d.sends, d.id).not.toBe('');
    }
    expect(declared.map((d) => d.host)).toContain('api.github.com');
  });

  it('and nothing in the update surface holds a reference to a learner', () => {
    /*
     * The other half of «offline is safe»: what would be *sent* if a request happened.
     * The update path has no vault, no learner code and no profile in it — a check
     * carries the request and nothing else, and that is enforced by the update files
     * having nothing else to carry.
     */
    const files = [
      join(repoRoot, 'app', 'packages', 'providers', 'src', 'releases.ts'),
      join(repoRoot, 'app', 'packages', 'shell', 'src', 'corpus', 'destinations.ts'),
      join(repoRoot, 'app', 'packages', 'core', 'src', 'corpus-update', 'manifest.ts'),
    ];
    for (const f of files) {
      const code = readFileSync(f, 'utf8')
        .replace(/\/\*[\s\S]*?\*\//g, '').replace(/^[ \t]*\/\/.*$/gm, '');
      for (const word of ['learnerCode', 'currentVault', 'loadLearner', 'profile.']) {
        expect(code, `${f} · ${word}`).not.toContain(word);
      }
    }
  });
});

/**
 * The launch check, if she asked for one (034 T024, FR-3202, research R5).
 *
 * Pure, so the three things that make it safe are checkable without a clock: consent,
 * a weekly bound, and silence.
 */
describe('a check at launch happens only because she said so', () => {
  it('absent consent is no, which is the requirement and not a default', async () => {
    const { mayCheckAtLaunch } = await import('../src/updates/notice.js');
    expect(mayCheckAtLaunch({}, '2026-09-20T08:00:00Z')).toBe(false);
    expect(mayCheckAtLaunch({ checkAtLaunch: false }, '2026-09-20T08:00:00Z')).toBe(false);
  });

  it('and with consent it runs, at most weekly', async () => {
    /*
     * «At launch» in a school means every morning. A daily outbound request on a
     * schedule nobody asked for is the thing the consent was supposed to be about.
     */
    const { mayCheckAtLaunch } = await import('../src/updates/notice.js');
    const on = { checkAtLaunch: true };
    expect(mayCheckAtLaunch(on, '2026-09-20T08:00:00Z')).toBe(true);
    expect(mayCheckAtLaunch(
      { ...on, lastLaunchCheck: '2026-09-19T08:00:00Z' }, '2026-09-20T08:00:00Z')).toBe(false);
    expect(mayCheckAtLaunch(
      { ...on, lastLaunchCheck: '2026-09-10T08:00:00Z' }, '2026-09-20T08:00:00Z')).toBe(true);
  });

  it('and an unreadable stamp allows it rather than blocking it for ever', async () => {
    /*
     * The failure directions are not symmetric. A check too many is one anonymous
     * request; a check never again is a teacher who never learns about the fix she is
     * stranded on.
     */
    const { mayCheckAtLaunch } = await import('../src/updates/notice.js');
    expect(mayCheckAtLaunch(
      { checkAtLaunch: true, lastLaunchCheck: 'ayer' }, '2026-09-20T08:00:00Z')).toBe(true);
  });

  it('a failing check is silent, and still counts as having run', async () => {
    /*
     * Silent, because a school with no outbound HTTP at 9am is the ordinary case and an
     * error there teaches her the application is broken. And it counts, so a permanently
     * offline machine tries once a week rather than on every launch.
     */
    const { launchCheck } = await import('../src/updates/notice.js');
    const dir = await mkdtemp(join(tmpdir(), 'rampa-launch-'));
    await writeFile(join(dir, 'settings.json'), JSON.stringify({ checkAtLaunch: true }));

    const ran = await launchCheck({
      settingsDir: dir, now: '2026-09-20T08:00:00Z',
      check: async () => { throw new Error('no network'); },
    });
    expect(ran.ran).toBe(true);

    // And the second launch that morning does not.
    const again = await launchCheck({
      settingsDir: dir, now: '2026-09-20T09:00:00Z', check: async () => {},
    });
    expect(again.ran).toBe(false);
    await rm(dir, { recursive: true, force: true });
  });

  it('and with no consent the check function is never even called', async () => {
    const { launchCheck } = await import('../src/updates/notice.js');
    const dir = await mkdtemp(join(tmpdir(), 'rampa-launch-'));
    let called = false;
    const ran = await launchCheck({
      settingsDir: dir, now: '2026-09-20T08:00:00Z',
      check: async () => { called = true; },
    });
    expect(ran.ran).toBe(false);
    expect(called).toBe(false);
    await rm(dir, { recursive: true, force: true });
  });

  /**
   * Never during a rehearsal (`035` T020, FR-3302 · `034` T024).
   *
   * `035`'s whole claim is **zero requests**, counted in Chromium's session and in Node's
   * `fetch`, on the one path built to be provably offline — a fictional child, no
   * connection, nothing spent. A launch check firing while she shows the sample to a
   * colleague breaks that claim, and breaks it **silently**, because this check says
   * nothing either way.
   *
   * `035` T020 said «if `034`'s notice is not yet built, record the obligation in the
   * BACKLOG instead of building a stub; a task that cannot land must not land as an if».
   * It is built, so this is the coordination it was waiting for.
   */
  it('does not fire during a rehearsal, and does not spend the week on it', async () => {
    const { launchCheck } = await import('../src/updates/notice.js');
    const dir = await mkdtemp(join(tmpdir(), 'rampa-launch-'));
    await writeFile(join(dir, 'settings.json'), JSON.stringify({ checkAtLaunch: true }));

    let called = false;
    const during = await launchCheck({
      settingsDir: dir, now: '2026-09-20T08:00:00Z',
      check: async () => { called = true; },
      rehearsing: async () => true,
    });
    expect(during.ran).toBe(false);
    expect(during.because).toBe('rehearsal');
    expect(called, 'a request left during a rehearsal').toBe(false);

    /*
     * And the week is **not** spent on it.
     *
     * No stamp was written, so the next launch outside a rehearsal checks. Recording the
     * stamp would mean a teacher who rehearsed on Monday morning gets no check until the
     * following Monday — a refusal turning into a week of silence, which is the failure
     * direction `mayCheckAtLaunch` already argues is the worse one.
     */
    const after = await launchCheck({
      settingsDir: dir, now: '2026-09-20T08:05:00Z',
      check: async () => { called = true; },
      rehearsing: async () => false,
    });
    expect(after.ran).toBe(true);
    expect(called).toBe(true);
    await rm(dir, { recursive: true, force: true });
  });

  /**
   * And the check the button starts is the **same call** (`034` T024).
   *
   * That promise — «one implementation shared with the button, so there is exactly one
   * place a check can start from» — was not true: the work lived in a handler body, which
   * is why `launchCheck` had nothing to call and ended up wired to nobody. Asserted
   * structurally, because what must hold is that neither path grows its own copy of
   * «connect, list, hash, scan».
   */
  it('starts the same check the button does, from one place', async () => {
    const src = await readFile(
      join(dirname(new URL(import.meta.url).pathname), '..', 'src', 'updates', 'corpus.ts'),
      'utf8');

    // The handler delegates rather than doing the work.
    expect(src).toMatch(/handle\('corpus:updateLook'[\s\S]{0,120}return lookForUpdate\(/);
    // And the connecting happens once in the file, inside that function.
    expect([...src.matchAll(/newestCorpusRelease\(/g)]).toHaveLength(1);

    const links = await readFile(
      join(dirname(new URL(import.meta.url).pathname), '..', 'src', 'corpus', 'links.ts'),
      'utf8');
    // The caller that was missing entirely.
    expect(links, 'nothing calls launchCheck').toMatch(/launchCheck\(\{/);
    expect(links, 'the launch check does not know about rehearsals').toMatch(/rehearsing:/);
  });
});
